version: 1.0.0.{build}
branches:
  only:
  - master
  - develop

image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug

platform:
  - Win32
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  GENERATOR: Visual Studio 14 2015

matrix:
  fast_finish: true

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
      BOOST_ROOT: C:\Libraries\boost_1_67_0
      GENERATOR: Visual Studio 15 2017

before_build:
  - if exist build\ (rmdir /S /Q build)
  - set "INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\installed"
  - if exist %INSTALL_DIR%\ (rmdir /S /Q %INSTALL_DIR%)
  - mkdir build
  - cd build
  - if %platform% == x64 (set "GENERATOR=%GENERATOR% Win64")
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% ..

build:
  project: build/nowide.sln
  parallel: true

test_script:
  - ctest --output-on-failure -C %configuration% --parallel 4
  # Build consumer example test
  - cmake --build . --config %configuration% --target install
  - del /F /S /Q *
  - cmake ../test/exampleProject -G "%GENERATOR%" -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\installed
  - cmake --build . --config %configuration%
  - ctest --output-on-failure -C %configuration% --parallel 4